### ISSUE TITLE
Generic version/linux compatibility

### ISSUE THREAD

**Issue by BlueDrink9** [gmoe/tmux-wifi#3]
This is a nice plugin. At some point, I may want to fork this and create a generic version that allows different programs to be parsed for SSID etc (other than airport, eg iwconfig).

Would you be happy with this/would you accept PRs?

I'd probably refactor out any airport reference/parsing into functions like get_ssid, get_strength, and keep them in different files sourced depending on available programs. If you are happy to get the ball rolling for the airport stuff, that would also be really cool

**Comment by BlueDrink9** [comment]
Info about anything else in there you can think of that is OSX-specific would be neat too!

**Comment by gmoe** [comment]
@BlueDrink9 I would love a PR for Linux support if you have time for it!

I went ahead and refactored the scripts in https://github.com/gmoe/tmux-wifi-macos/commit/3d1122b4610a7213810e524ae943cc2b0a5a4e8c with placeholders for Linux support, feel free to adjust as needed.

**Comment by BlueDrink9** [comment]
Fixed in #4
