### ISSUE TITLE
Add a feature to customize Wi-Fi status icons.

### ISSUE THREAD

**Issue by TsutomuNakamura** [gmoe/tmux-wifi#5]
I want to add a feature to customize wifi status icons in your great plugin. For example, we added tmux options in our ~/.tmux.conf then icons will change like below.

```
set -g @tmux_wifi_icon_5 '😆'
set -g @tmux_wifi_icon_4 '😀'
set -g @tmux_wifi_icon_3 '😉'
set -g @tmux_wifi_icon_2 '😐'
set -g @tmux_wifi_icon_1 '😑'
set -g @tmux_wifi_icon_off '😱'

set -g status-right "#{wifi_ssid} #{wifi_icon} #{wifi_strength}"
```

Result:
![p](https://user-images.githubusercontent.com/10674169/59727481-d93a9b80-9270-11e9-9c35-7afbd9d241d1.png)

**Comment by gmoe** [comment]
Fixed in https://github.com/gmoe/tmux-wifi/pull/7, thanks again @TsutomuNakamura!
